# docker compose file that sets up mongodb and the app
version: '3.1'
services:
  mongo:
    image: mongo:4.4.6
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
  app:
    image: node:16.10.0
    container_name: app
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
    depends_on:
      - mongo
    command: bash -c "cd /app && npm install && npm test -- ./test.sqlite3 mongodb://user:pass@mongo:27017/test"